function getArray(arrayName){
    return arrayName;
}

module.exports.getLabTitles = function(){
     return getArray(labTitles);
};
module.exports.getMembers = function(){
    return getArray(Members);
};
module.exports.getFormerTitles = function(){
    return getArray(former);
};
module.exports.getFormerMembers = function(){
    return getArray(formerMembers);
};
module.exports.getYears = function(){
    return getArray(years);
};
module.exports.getPapers = function(){
    return getArray(papers);
};
var labTitles = ['Principle Investigator', 'Postdoctoral Researchers', 'Graduate Students', 'Undergraduate Students'];

var Members = [
        {name: 'Dr. Colin Johnson',
        image: '/images/Johnson Base Final.jpg',
        title: 'Principle Investigator',
        current: true,
        credentials: 'Ph.D 2005 - University of Illinois, Urbana Champaign; Postdoc 2005-2007 - University of Pennsylvania; Postdoc 2007-2011 - University of Wisconsin, Madison',
        bio: 'Colin is a fan of running, comics, cycling, and beans.'},
        {name: 'Dr. Josephine Bonventre',
        image: '/images/bonventre1.jpg',
        title: 'Postdoctoral Researchers',
        current: true,
        credentials: 'This section is for credentials.',
        bio: 'This section is for a mini-bio.'},
        {name: 'Aayushi Manchanda',
        image: '/images/manchanda.jpg',
        title: 'Graduate Students',
        current: true,
        credentials: 'PhD. Candidate - Molecular & Cellular Biology',
        bio: 'Aayushi enjoys puppies and protein pull downs'},
        {name: 'Shauna Otto',
        image: '/images/otto1.jpg',
        title: 'Graduate Students',
        current: true,
        credentials: 'PhD. Candidate - Biochemistry & Biophysics',
        bio: 'Shauna enjoys crafting, karaoke, and membrane transport.'},
        {name: 'James Miyasaki',
        image: '/images/miyasaki.png',
        title: 'Graduate Students',
        current: true,
        credentials: 'Master\'s Student - Biochemistry & Biophysics',
        bio: 'This section is for a mini-bio.'},
        {name: 'Sabrina (Jou-Ying) Lin',
        image: '',
        title: 'Graduate Students',
        current: true,
        credentials: 'Master\'s Student - Biochemistry & Biophysics',
        bio: 'This section is for a mini-bio.'},
        {name: 'Tanushri Kumar',
        image: '/images/kumar.jpg',
        title: 'Undergraduate Students',
        current: true,
        credentials: 'Senior - Biochemistry & Molecular Biology',
        bio: 'This section is for a mini-bio.'},
        {name: 'Rebecca France',
        image: '/images/france.jpg',
        title: 'Undergraduate Students',
        current: true,
        credentials: 'Junior - Biochemistry & Molecular Biology',
        bio: 'This section is for a mini-bio.'},
        {name: 'Susmitha Matlapudi',
        image: '/images/matlapudi.png',
        title: 'Undergraduate Students',
        current: true,
        credentials: 'Senior - Microbiology',
        bio: 'This section is for a mini-bio.'},
        {name: 'Chapman Kuykendall',
        image: '/images/kuykendall.jpg',
        title: 'Undergraduate Students',
        current: true,
        credentials: 'Junior - Biochemistry & Molecular Biology',
        bio: 'Chapman is a junior BMB major originally from Phoenix, Oregon. He enjoys reading, hiking, cooking, and irritating his cat, Gato.'},
];

var former = ['Postdoctoral Researchers', 'Graduate Students', 'Undergraduate Students'];

var formerMembers = [
        {name:'Dr. Nazish Abdullah',
        title: 'Postdoctoral Researchers',
        credentials:'',
        researchTopic: 'Dysferlin Biochemistry',
        researchUrl: '',
        currentJob:'Scientist at Regeneron Pharmaceuticals',
        currentJobUrl:'http://www.regeneron.com',
        osuYears: '2011-2014'},
        {name:'Dr. Naomi Marty-Howard',
        title: 'Postdoctoral Researchers',
        credentials:'',
        researchTopic: 'Ferlin-related membrane trafficking',
        researchUrl: '',
        currentJob:'Regional Finance Officer at Ontario Ministry of Natural Resources & Forestry',
        currentJobUrl:'',
        osuYears: '2011-2012'},
        {name:'Dr. Nicole Hams',
        title: 'Graduate Students',
        credentials:'M.S., PhD. - Biochemistry & Biophysics',
        researchTopic: 'Developing single molecule methods to study conformational dynamics of ferlin proteins',
        researchUrl: '',
        currentJob:'Postdoctoral Researcher in the Bartholomew Lab at OSU',
        currentJobUrl:'https://microbiology.science.oregonstate.edu/content/dr-jerri-bartholomew',
        osuYears: '2013-2018'},
        {name:'Dr. Chelsea Wolk-Weiss (nee Holman)',
        title: 'Graduate Students',
        credentials:'PhD. - Biochemistry & Biophysics',
        researchTopic: 'Initial in vitro and in vivo Characterization of the Membrane Trafficking Protein Fer1L6',
        researchUrl: 'https://search.library.oregonstate.edu/permalink/f/ueodtl/CP71253039520001451',
        currentJob:'UW Biotechnology Project Management Program',
        currentJobUrl:'',
        osuYears: '2011-2017'},
        {name:'Dr. Sara Codding',
        title: 'Graduate Students',
        credentials:'PhD. - Biochemistry & Biophysics',
        researchTopic: 'Functional and Structural Analyses of Three Distinct proteins by Biochemical and Biophysical Techniques',
        researchUrl: 'https://search.library.oregonstate.edu/permalink/f/ueodtl/CP71252910560001451',
        currentJob:'Postdoctoral Researcher in the Trudeau Lab at the University of Maryland School of Medicine',
        currentJobUrl:'https://www.medschool.umaryland.edu/profiles/Trudeau-Matthew/',
        osuYears: '2010-2016'},
        {name:'Dr. Murugesh Padmanarayana',
        title: 'Graduate Students',
        credentials: 'M.S., PhD. - Biochemistry & Biophysics',
        researchTopic: 'Characterizing the Functional Properties of Otoferlin, Essential for Neurotransmission in Inner Hair Cells of the Cochlea',
        researchUrl: 'https://search.library.oregonstate.edu/permalink/f/ueodtl/CP71252901380001451',
        currentJob: 'Postdoctoral Researcher in the Dittman Lab at Weill Cornell Medical School',
        currentJobUrl: 'https://sites.google.com/site/dittmanlabhomepage/people',
        osuYears: '2011-2016'},
        {name:'Dr. Paroma Chatterjee',
        title: 'Graduate Students',
        credentials: 'PhD. - Molecular and Cellular Biology',
        researchTopic: 'Establishing Larval Zebrafish as an In Vivo Model Organism for Characterizing the Roles of Otoferlin, a Sensory Hair Cell Protein Essential for Hearing',
        researchUrl: 'https://ir.library.oregonstate.edu/concern/graduate_thesis_or_dissertations/6395wb890',
        currentJob: 'Postdoctoral Researcher in the Barr-Gillespie Lab at the Vollum Institute-OHSU',
        currentJobUrl: 'https://www.ohsu.edu/barr-gillespie-lab/lab-members',
        osuYears: '2011-2016'},
        {name:'Olivia Ozguc',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: '',
        researchTopic: '',
        researchUrl: '',
        currentJob: '',
        currentJobUrl: '',
        osuYears: '2017-2018'},
        {name:'Trisha Chau',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: 'Honor\'s College Thesis Student, SURE Awardee 2015, URISC Awardee 2015',
        researchTopic: '',
        researchUrl: '',
        currentJob: 'Medical Student - OHSU',
        currentJobUrl: '',
        osuYears: '2015-2019'},
        {name:'Blake Hakkila',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: 'Honor\'s College Thesis Student, SURE Awardee 2015',
        researchTopic: '',
        researchUrl: '',
        currentJob: 'Development Engineer - e-MSion Inc',
        currentJobUrl: '',
        osuYears: '2016-2018'},
        {name:'Scott Hershberger',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: 'CURE Awardee 2015',
        researchTopic: '',
        researchUrl: '',
        currentJob: '',
        currentJobUrl: '',
        osuYears: '2015-2018'},
        {name:'Natalie Syverud',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: '',
        researchTopic: '',
        researchUrl: '',
        currentJob: '',
        currentJobUrl: '',
        osuYears: '2016'},
        {name:'Franco Felix',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: '',
        researchTopic: '',
        researchUrl: '',
        currentJob: '',
        currentJobUrl: '',
        osuYears: '2016'},
        {name:'Dana Palmer',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: '',
        researchTopic: '',
        researchUrl: '',
        currentJob: '',
        currentJobUrl: '',
        osuYears: '2016'},
        {name:'Trenity Norton',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: '',
        researchTopic: '',
        researchUrl: '',
        currentJob: '',
        currentJobUrl: '',
        osuYears: '2014-2015'},
        {name:'Jacob Hugel',
        title: 'Undergraduate Students',
        credentials: 'Biochemistry & Biophysics',
        honors: 'Honor\'s College Thesis Student, URISC-START Awardee 2011',
        researchTopic: '',
        researchUrl: '',
        currentJob: 'Medical Student - Geisinger Commonwealth School of Medicine',
        currentJobUrl: '',
        osuYears: '2011-2015'},
];

var years = [2019, 2017, 2016];

var papers = [
	{title: 'Fer1L6 is essential for the development of vertebrate muscle tissue in zebrafish.',
	citation: 'Mol Biol Cell 2019 Feb 1 ;30(3):293-301.',
	authors: 'Bonventre JA, Holman C, Manchanda A, Codding SJ, Chau T, Huegel J, Barton C, Tanguay R, Johnson CP',
	abstract: 'The precise spatial and temporal expression of genes is essential for proper organismal development. Despite their importance, however, many developmental genes have yet to be identified. We have determined that Fer1l6, a member of the ferlin family of genes, is a novel factor in zebrafish development. We find that Fer1l6 is expressed broadly in the trunk and head of zebrafish larvae and is more restricted to gills and female gonads in adult zebrafish. Using both genetic mutant and morpholino knockdown models, we found that loss of Fer1l6 led to deformation of striated muscle tissues, delayed development of the heart, and high morbidity. Further, expression of genes associated with muscle cell proliferation and differentiation were affected. Fer1l6 was also detected in the C2C12 cell line, and unlike other ferlin homologues, we found Fer1l6 expression was independent of the myoblast-to-myotube transition. Finally, analysis of cell and recombinant protein-based assays indicate that Fer1l6 colocalizes with syntaxin 4 and vinculin, and that the putative C2 domains interact with lipid membranes. We conclude that Fer1l6 has diverged from other vertebrate ferlins to play an essential role in zebrafish skeletal and cardiac muscle development.',
	url: 'https://www.ncbi.nlm.nih.gov/pubmed/30516436',
	image: '/Papers/MBoC2019.JPG',
	year: 2019},
	{title: 'Otoferlin C2F Domain-Induced Changes in Membrane Structure Observed by Sum Frequency Generation.',
	citation: 'Biophys J. 2019 Sep 17. pii: S0006-3495(19)30784-2.',
	authors: 'Golbek TW, Padmanarayana M, Roeters SJ, Weidner T, Johnson CP, Baio JE.',
	abstract: 'Proteins that contain C2 domains are involved in a variety of biological processes, including encoding of sound, cell signaling, and cell membrane repair. Of particular importance is the interface activity of the C-terminal C2F domain of otoferlin due to the pathological mutations known to significantly disrupt the protein\'s lipid membrane interface binding activity, resulting in hearing loss. Therefore, there is a critical need to define the geometry and positions of functionally important sites and structures at the otoferlin-lipid membrane interface. Here, we describe the first in situ probe of the protein orientation of otoferlin\'s C2F domain interacting with a cell membrane surface. To identify this protein\'s orientation at the lipid interface, we applied sum frequency generation (SFG) vibrational spectroscopy and coupled it with simulated SFG spectra to observe and quantify the otoferlin C2F domain interacting with model lipid membranes. A model cell membrane was built with equal amounts of phosphatidylserine and phosphatidylcholine. SFG measurements of the lipids that make up the model membrane indicate a 62% increase in amplitude from the SFG signal near 2075 cm-1 upon protein interaction, suggesting domain-induced changes in the orientation of the lipids and possible membrane curvature. This increase is related to lipid ordering caused by the docking interaction of the otoferlin C2F domain. SFG spectra taken from the amide-I region contain features near 1630 and 1670 cm-1 related to the C2F domains beta-sandwich secondary structure, thus indicating that the domain binds in a specific orientation. By mapping the simulated SFG spectra to the experimentally collected SFG spectra, we found the C2F domain of otoferlin orients 22° normal to the lipid surface. This information allows us to map what portion of the domain directly interacts with the lipid membrane.',
	url: 'https://www.ncbi.nlm.nih.gov/pubmed/31587832',
	image: '/Papers/BPJ2019.JPG',
	year: 2019},
];